### ISSUE TITLE
Class AppHostBD\Fpdf\Fpdf\FPDF does not exist

### ISSUE THREAD

**Issue by thomasjeffrey** [apphostbd/laravel-fpdf#1]
Everything works well on localhost but on sharehosting, it is giving me this error "Class AppHostBD\Fpdf\Fpdf\FPDF does not exist"

**Comment by farhanswe** [comment]
Controller or Blade Page: 

`use Fpdf;`

**Comment by farhanswe** [comment]
package update and your issue is solve
